# Generated by Django 6.0.4 on 2026-05-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_mascota_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='numero_chip',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
